---
# A role to Install PostgreSQL
# To Check if PostgreSQL is already installed.
#- name: Find pg_hba.conf
#  find:
#    paths: /opt/PostgreSQL
#    patterns: "test.txt"
#    recurse: yes
#  register: file_found

#- name: Debug log
#  debug: var=file_found

#- name: Check if PostgreSQL already started
#  stat:
#    path: "/opt/PostgreSQL/{{pg_version}}/data/pg_hba.conf"
#  register: stat_result

# To Install PostgreSQL
- name: Install available PostgreSQL
  yum:
    name: postgresql-server
    state: latest

#  command: "yum install -y postgresql-server"
#  when: file_found.files[0] != ""
#  when: stat_result.stat.exists == True

# To enable PostgreSQL to start at Linux boot
- name: Enable PostgreSQL at Linux Boot
  service:
    name: postgresql
    enabled: yes
  notify: "restart postgresql"
